sudo: false

language: php

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --prefer-dist
script: vendor/bin/phpunit